drop table if exists l_user_goods CASCADE;
drop table if exists m_goods CASCADE;
/**/drop table if exists m_message CASCADE;
drop table if exists m_roles CASCADE;
drop table if exists m_users CASCADE;
create table l_user_goods
(
    good_id bigint not null,
    user_id bigint not null,
    primary key (good_id, user_id)
);
create table m_goods
(
    id        bigint generated by default as identity,
    good_name varchar(255),
    primary key (id)
);
/**/create table m_message
(
    id      bigint generated by default as identity,
    text    varchar(255),
    user_id bigint,
    primary key (id)
);
create table m_roles
(
    user_id bigint not null, role_name varchar(255)
);
create table m_users
(
    id       bigint generated by default as identity,
    email    varchar(255),
    username varchar(255),
    password varchar(255),
    primary key (id)
);
alter table l_user_goods
    add constraint l_user_goods_user_id_fk foreign key (user_id) references m_users;
alter table l_user_goods
    add constraint l_user_goods_good_id_fk foreign key (good_id) references m_goods;
/**/alter table m_message
    add constraint m_message_user_id_fk foreign key (user_id) references m_users;
alter table m_roles
    add constraint m_roles_user_id_fk foreign key (user_id) references m_users;
